# Generated by Django 4.1.5 on 2023-01-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_snippet_highlighted_snippet_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='highlighted',
            field=models.TextField(),
        ),
    ]
